// apps/stress-test/src/shared/react/TestMount.tsx
import * as React from 'react';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';
import { ReactSelectorTree } from './ReactSelectorTree';
import type { TestProps } from './types';

export const TestMount: React.FC<TestProps> = ({ tree, selectors, componentRenderer, testOptions }) => {
  // eslint-disable-next-line no-restricted-properties
  React.useLayoutEffect(() => {
    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }
    performanceMeasure();
  }, []);

  return <ReactSelectorTree tree={tree} componentRenderer={componentRenderer} />;
};

// apps/stress-test/src/shared/wc/TestMount.ts
import { performanceMeasure } from '../utils/performanceMeasure';
import { TestOptions } from '../utils/testOptions';
import { SelectorTreeNode } from '../tree/types';
import { DOMSelectorTreeComponentRenderer } from '../vanilla/types';
import { WCTestTree } from './types';
import { WCSelectorTree } from './WCSelectorTree';
import { styleInjector } from '../css/injectStyles';

export class TestMount extends HTMLElement implements WCTestTree {
  constructor(
    tree: SelectorTreeNode,
    selectors: string[],
    componentRenderer: DOMSelectorTreeComponentRenderer,
    testOptions: TestOptions,
  ) {
    super();

    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }

    const domTree = new WCSelectorTree(componentRenderer, testOptions);
    domTree.tree = tree;

    this.appendChild(domTree);
    requestAnimationFrame(() => performanceMeasure());
  }
}

window.customElements.define('wc-test-mount', TestMount);
