// apps/stress-test/src/shared/react/TestReRenderAll.tsx
import * as React from 'react';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';
import { ReactSelectorTree } from './ReactSelectorTree';
import type { TestProps } from './types';

export const TestReRenderAll: React.FC<TestProps> = ({ tree, selectors, componentRenderer, testOptions }) => {
  const [theTree, setTheTree] = React.useState<TestProps['tree'] | undefined>();

  React.useEffect(() => {
    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }
  }, []);

  React.useEffect(() => {
    if (theTree === undefined && tree) {
      setTheTree(tree);

      setTimeout(() => {
        setTheTree(undefined);

        setTimeout(() => {
          setTheTree(tree);
          performanceMeasure();
        }, 2000);
      }, 2000);
    }
  }, [tree]);

  return <ReactSelectorTree tree={theTree} componentRenderer={componentRenderer} />;
};

// apps/stress-test/src/shared/wc/TestReRenderAll.ts
import { TestOptions } from '../utils/testOptions';
import { WCSelectorTree } from './WCSelectorTree';
import { WCTestTree } from './types';
import { SelectorTreeNode } from '../tree/types';
import { DOMSelectorTreeComponentRenderer } from '../vanilla/types';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';

export class TestReRenderAll extends HTMLElement implements WCTestTree {
  constructor(
    tree: SelectorTreeNode,
    selectors: string[],
    componentRenderer: DOMSelectorTreeComponentRenderer,
    testOptions: TestOptions,
  ) {
    super();

    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }

    const domTree = new WCSelectorTree(componentRenderer, testOptions);
    domTree.tree = tree;
    this.appendChild(domTree);

    setTimeout(() => {
      domTree.tree = null;

      setTimeout(() => {
        domTree.tree = tree;
        requestAnimationFrame(() => performanceMeasure());
      }, 2000);
    }, 2000);
  }
}

window.customElements.define('wc-test-re-render-all', TestReRenderAll);
