// packages/charts/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx
import * as React from 'react';
import { useHorizontalBarChartStyles_unstable } from './useHorizontalBarChartStyles.styles';
import { ChartProps, HorizontalBarChartProps, ChartDataPoint, RefArrayData, HorizontalBarChartVariant } from './index';
import { convertToLocaleString } from '../../utilities/locale-util';
import {
  DataVizGradientPalette,
  formatValueWithSIPrefix,
  getAccessibleDataObject,
  getGradientFromToken,
  getNextGradient,
  useRtl,
} from '../../utilities/index';
import { useId } from '@fluentui/react-utilities';
import { useFocusableGroup } from '@fluentui/react-tabster';
import { ChartPopover } from '../CommonComponents/ChartPopover';
import { FocusableTooltipText } from '../../utilities/FocusableTooltipText';

/**
 * HorizontalBarChart is the context wrapper and container for all HorizontalBarChart content/controls,
 * It has no direct style or slot opinions.
 *
 * HorizontalBarChart also provides API interfaces for callbacks that will occur on navigation events.
 */
export const HorizontalBarChart: React.FunctionComponent<HorizontalBarChartProps> = React.forwardRef<
  HTMLDivElement,
  HorizontalBarChartProps
>((props, forwardedRef) => {
  let _barHeight: number;
  //let _classNames: IProcessedStyleSet<IHorizontalBarChartStyles>;
  const _uniqLineText: string = '_HorizontalLine_' + Math.random().toString(36).substring(7);
  const _refArray: RefArrayData[] = [];
  let _calloutAnchorPoint: ChartDataPoint | null;
  const _isRTL: boolean = useRtl();
  const barChartSvgRef: React.RefObject<SVGSVGElement> = React.createRef<SVGSVGElement>();
  const _emptyChartId: string = useId('_HBC_empty');
  const _gradientId = useId('HBC_Gradient');

  const [hoverValue, setHoverValue] = React.useState<string | number | Date | null>('');
  const [lineColor, setLineColor] = React.useState<string>('');
  const [legend, setLegend] = React.useState<string | null>('');
  const [xCalloutValue, setXCalloutValue] = React.useState<string | undefined>('');
  const [yCalloutValue, setYCalloutValue] = React.useState<string | undefined>('');
  const [barCalloutProps, setBarCalloutProps] = React.useState<ChartDataPoint>();
  const [barSpacingInPercent, setBarSpacingInPercent] = React.useState<number>(0);
  const [isPopoverOpen, setPopoverOpen] = React.useState<boolean>(false);
  const [clickPosition, setClickPosition] = React.useState({ x: 0, y: 0 });

  function _refCallback(element: SVGGElement, legendTitle: string | undefined): void {
    _refArray.push({ index: legendTitle, refElement: element });
  }

  function _hoverOn(
    event: React.MouseEvent<SVGRectElement, MouseEvent>,
    hoverVal: string | number | Date,
    point: ChartDataPoint,
  ): void {
    if ((!isPopoverOpen || legend !== point.legend!) && _calloutAnchorPoint !== point) {
      _calloutAnchorPoint = point;
      updatePosition(event.clientX, event.clientY);
      setHoverValue(hoverVal);
      setLineColor(point.gradient![0]);
      setLegend(point.legend!);
      setXCalloutValue(point.xAxisCalloutData!);
      setYCalloutValue(point.yAxisCalloutData!);
      setBarCalloutProps(point);
      // ToDo - Confirm setting multiple state variables like this is performant.
    }
  }

  function _hoverOff(): void {
    /*ToDo. To fix*/
  }

  const _handleChartMouseLeave = () => {
    _calloutAnchorPoint = null;
    if (isPopoverOpen) {
      setPopoverOpen(false);
      setHoverValue('');
      setLineColor('');
      setLegend('');
    }
  };

  const _adjustProps = (): void => {
    _barHeight = props.barHeight || 12;
  };

  const _getChartDataText = (data: ChartProps) => {
    /* return props.barChartCustomData ? (
        <div role="text">{props.barChartCustomData(data)}</div>
      ) : ( */
    return _getDefaultTextData(data);
    //)
  };

  function _getDefaultTextData(data: ChartProps): JSX.Element {
    const { culture } = props;
    const chartDataMode = props.chartDataMode || 'default';
    const chartData: ChartDataPoint = data!.chartData![0];
    const x = chartData.horizontalBarChartdata!.x;
    const y = chartData.horizontalBarChartdata!.y;

    const accessibilityData = getAccessibleDataObject(data.chartDataAccessibilityData!, 'text', false);
    switch (chartDataMode) {
      case 'default':
        return (
          <div className={classes.chartTitleRight} {...accessibilityData}>
            {convertToLocaleString(x, culture)}
          </div>
        );
      case 'fraction':
        return (
          <div {...accessibilityData}>
            <span className={classes.chartTitleRight}>{convertToLocaleString(x, culture)}</span>
            <span className={classes.chartDataTextDenominator}>{' / ' + convertToLocaleString(y, culture)}</span>
          </div>
        );
      case 'percentage':
        const dataRatioPercentage = `${convertToLocaleString(Math.round((x / y) * 100), culture)}%`;
        return (
          <div className={classes.chartTitleRight} {...accessibilityData}>
            {dataRatioPercentage}
          </div>
        );
    }
  }

  function _createBenchmark(data: ChartProps): JSX.Element {
    const totalData = data.chartData![0].horizontalBarChartdata!.y;
    const benchmarkData = data.chartData![0].data;
    const benchmarkRatio = Math.round(((benchmarkData ? benchmarkData : 0) / totalData) * 100);

    const benchmarkStyles = {
      left: 'calc(' + benchmarkRatio + '% - 4px)',
    };

    return (
      <div className={classes.benchmarkContainer}>
        <div className={classes.triangle} style={benchmarkStyles} />
      </div>
    );
  }

  /**
   * This functions returns an array of <rect> elements, which form the bars
   * For each bar an x value, and a width needs to be specified
   * The computations are done based on percentages
   * Extra margin is also provided, in the x value to provide some spacing in between the bars
   */

  function _createBars(data: ChartProps, dataPointIndex: number): JSX.Element[] {
    const noOfBars =
      data.chartData?.reduce((count: number, point: ChartDataPoint) => (count += (point.data || 0) > 0 ? 1 : 0), 0) ||
      1;
    const totalMarginPercent = barSpacingInPercent * (noOfBars - 1);

    // calculating starting point of each bar and it's range
    const startingPoint: number[] = [];
    const total = data.chartData!.reduce(
      (acc: number, point: ChartDataPoint) =>
        acc + (point.horizontalBarChartdata!.x ? point.horizontalBarChartdata!.x : 0),
      0,
    );
    let prevPosition = 0;
    let value = 0;

    let sumOfPercent = 0;
    data.chartData!.map((point: ChartDataPoint, index: number) => {
      const pointData = point.horizontalBarChartdata!.x ? point.horizontalBarChartdata!.x : 0;
      value = (pointData / total) * 100;
      if (value < 0) {
        value = 0;
      } else if (value < 1 && value !== 0) {
        value = 1;
      }
      sumOfPercent += value;

      return sumOfPercent;
    });

    /**
     * The %age of the space occupied by the margin needs to subtracted
     * while computing the scaling ratio, since the margins are not being
     * scaled down, only the data is being scaled down from a higher percentage to lower percentage
     * Eg: 95% of the space is taken by the bars, 5% by the margins
     * Now if the sumOfPercent is 120% -> This needs to be scaled down to 95%, not 100%
     * since that's only space available to the bars
     */
    const scalingRatio = sumOfPercent !== 0 ? (sumOfPercent - totalMarginPercent) / 100 : 1;

    const bars = data.chartData!.map((point: ChartDataPoint, index: number) => {
      const pointData = point.horizontalBarChartdata!.x ? point.horizontalBarChartdata!.x : 0;
      if (index > 0) {
        prevPosition += value;
      }
      value = (pointData / total) * 100;
      if (value < 0) {
        value = 0;
      } else if (value < 1 && value !== 0) {
        value = 1 / scalingRatio;
      } else {
        value = value / scalingRatio;
      }
      startingPoint.push(prevPosition);

      const xValue = point.horizontalBarChartdata!.x;
      const placeholderIndex = 1;

      // Render bar label instead of placeholder bar for absolute-scale variant
      if (index === placeholderIndex && props.variant === HorizontalBarChartVariant.AbsoluteScale) {
        if (props.hideLabels) {
          return <text key={index} />;
        }

        const barValue = data.chartData![0].horizontalBarChartdata!.x;

        return (
          <text
            key={index}
            x={`${_isRTL ? 100 - startingPoint[index] : startingPoint[index]}%`}
            y={_barHeight / 2}
            dominantBaseline="central"
            transform={`translate(${_isRTL ? -4 : 4})`}
            className={classes.barLabel}
            aria-hidden={true}
          >
            {formatValueWithSIPrefix(barValue)}
          </text>
        );
      }

      const gradientId = _gradientId + `_${dataPointIndex}_${index}`;

      return (
        <>
          <defs>
            <linearGradient id={gradientId}>
              <stop offset="0" stopColor={point.gradient?.[0]} />
              <stop offset="100%" stopColor={point.gradient?.[1]} />
            </linearGradient>
          </defs>
          <rect
            key={index}
            x={`${
              _isRTL
                ? 100 - startingPoint[index] - value - index * barSpacingInPercent
                : startingPoint[index] + index * barSpacingInPercent
            }%`}
            y={0}
            rx={4}
            data-is-focusable={point.legend !== '' ? true : false}
            width={value + '%'}
            height={_barHeight}
            fill={`url(#${gradientId})`}
            onMouseOver={point.legend !== '' ? event => _hoverOn(event, xValue, point) : undefined}
            onFocus={point.legend !== '' ? event => _hoverOn.bind(event, xValue, point) : undefined}
            role="img"
            aria-label={_getAriaLabel(point)}
            onBlur={_hoverOff}
            onMouseLeave={_hoverOff}
            className={classes.barWrapper}
            tabIndex={point.legend !== '' ? 0 : undefined}
          />
        </>
      );
    });
    return bars;
  }

  function _addDefaultGradients(dataPoints: ChartDataPoint[], chartDataIndex: number): ChartDataPoint[] {
    return dataPoints
      ? dataPoints.map((item, index) => {
          return { ...item, gradient: item.gradient ?? getNextGradient(chartDataIndex, 0) };
        })
      : [];
  }

  const _getAriaLabel = (point: ChartDataPoint): string => {
    const pointLegend = point.xAxisCalloutData || point.legend;
    const yValue =
      point.yAxisCalloutData ||
      (point.horizontalBarChartdata ? `${point.horizontalBarChartdata.x}/${point.horizontalBarChartdata.y}` : 0);
    return point.callOutAccessibilityData?.ariaLabel || (pointLegend ? `${pointLegend}, ` : '') + `${yValue}.`;
  };

  function _isChartEmpty(): boolean {
    return !(props.data && props.data.length > 0);
  }

  function updatePosition(newX: number, newY: number): void {
    const threshold = 1; // Set a threshold for movement
    const { x, y } = clickPosition;

    // Calculate the distance moved
    const distance = Math.sqrt(Math.pow(newX - x, 2) + Math.pow(newY - y, 2));
    // Update the position only if the distance moved is greater than the threshold
    if (distance > threshold) {
      setClickPosition({ x: newX, y: newY });
      setPopoverOpen(true);
    }
  }

  React.useEffect(() => {
    const svgWidth = barChartSvgRef?.current?.getBoundingClientRect().width || 0;
    const MARGIN_WIDTH_IN_PX = 3;
    if (svgWidth) {
      const currentBarSpacing = (MARGIN_WIDTH_IN_PX / svgWidth) * 100;
      setBarSpacingInPercent(currentBarSpacing);
    }
  }, [barChartSvgRef]);

  const { data } = props;
  _adjustProps();
  const classes = useHorizontalBarChartStyles_unstable(props);
  const focusAttributes = useFocusableGroup();

  let datapoint: number | undefined = 0;

  return !_isChartEmpty() ? (
    <div className={classes.root} onMouseLeave={_handleChartMouseLeave}>
      {data!.map((points: ChartProps, index: number) => {
        // Add default gradients if not present
        points = { ...points, chartData: _addDefaultGradients(points.chartData!, index) };

        if (points.chartData && points.chartData![0] && points.chartData![0].horizontalBarChartdata!.x) {
          datapoint = points.chartData![0].horizontalBarChartdata!.x;
        } else {
          datapoint = 0;
        }
        points.chartData![1] = {
          legend: '',
          horizontalBarChartdata: {
            x: points.chartData![0].horizontalBarChartdata!.y - datapoint!,
            y: points.chartData![0].horizontalBarChartdata!.y,
          },
          gradient: getGradientFromToken(DataVizGradientPalette.disabled),
        };

        // Hide right side text of chart title for absolute-scale variant
        const chartDataText =
          props.variant === HorizontalBarChartVariant.AbsoluteScale ? null : _getChartDataText(points!);
        const bars = _createBars(points!, index);
        const keyVal = _uniqLineText + '_' + index;
        // ToDo - Showtriangle property is per data series. How to account for it in the new stylesheet
        /*         const classes = useHorizontalBarChartStyles_unstable(props.styles!, {
          width: props.width,
          showTriangle: !!points!.chartData![0].data,
          variant: props.variant,
        }); */

        return (
          <div key={index}>
            <div className={classes.items} {...focusAttributes}>
              <div className={classes.chartTitle}>
                {points!.chartTitle && (
                  <FocusableTooltipText
                    className={classes.chartTitleLeft}
                    content={points!.chartTitle}
                    accessibilityData={points!.chartTitleAccessibilityData}
                  />
                )}
                {chartDataText}
              </div>
              {points!.chartData![0].data && _createBenchmark(points!)}
              <svg ref={barChartSvgRef} className={classes.chart} aria-label={points!.chartTitle}>
                <g
                  id={keyVal}
                  key={keyVal}
                  ref={(e: SVGGElement) => {
                    _refCallback(e, points!.chartData![0].legend);
                  }}
                  // NOTE: points.chartData![0] contains current data value
                  onClick={() => {
                    const p = points!.chartData![0];
                    if (p && p.onClick) {
                      p.onClick();
                    }
                  }}
                >
                  {bars}
                </g>
              </svg>
            </div>
          </div>
        );
      })}
      <ChartPopover
        xCalloutValue={xCalloutValue}
        yCalloutValue={yCalloutValue}
        culture={props.culture ?? 'en-us'}
        clickPosition={clickPosition}
        isPopoverOpen={isPopoverOpen}
        legend={legend!}
        YValue={hoverValue!}
        color={lineColor}
        isCalloutForStack={false}
        customCallout={{
          customizedCallout: props.onRenderCalloutPerHorizontalBar
            ? props.onRenderCalloutPerHorizontalBar(barCalloutProps!)
            : undefined,
          customCalloutProps: props.customProps ? props.customProps(barCalloutProps!) : undefined,
        }}
        isCartesian={false}
      />
    </div>
  ) : (
    <div id={_emptyChartId} role={'alert'} style={{ opacity: '0' }} aria-label={'Graph has no data to display'} />
  );
  //TODO validate and fix focus border for issue for popover
});
HorizontalBarChart.displayName = 'HorizontalBarChart';

// packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.ts
import { attr, FASTElement, observable } from '@microsoft/fast-element';
import { create as d3Create, select as d3Select } from 'd3-selection';
import { getRTL, jsonConverter, SVG_NAMESPACE_URI, validateChartPropsArray } from '../utils/chart-helpers.js';
import { ChartDataPoint, ChartProps, Variant } from './horizontal-bar-chart.options.js';

/**
 * A Horizontal Bar Chart HTML Element.
 *
 * @public
 */
export class HorizontalBarChart extends FASTElement {
  @attr
  public variant?: Variant;

  @attr({ converter: jsonConverter })
  public data!: ChartProps[];

  @attr({ attribute: 'hide-ratio', mode: 'boolean' })
  public hideRatio: boolean = false;

  @attr({ attribute: 'hide-legends', mode: 'boolean' })
  public hideLegends: boolean = false;

  @attr({ attribute: 'hide-tooltip', mode: 'boolean' })
  public hideTooltip: boolean = false;

  @attr({ attribute: 'legend-list-label' })
  public legendListLabel?: string;

  @observable
  public uniqueLegends: ChartDataPoint[] = [];

  @observable
  public activeLegend: string = '';

  @observable
  public isLegendSelected: boolean = false;

  @observable
  public tooltipProps = {
    isVisible: false,
    legend: '',
    yValue: '',
    color: '',
    xPos: 0,
    yPos: 0,
  };

  public rootDiv!: HTMLDivElement;
  public chartContainer!: HTMLDivElement;

  private _isRTL: boolean = false;
  private barHeight: number = 12;
  private _bars: SVGRectElement[] = [];

  connectedCallback() {
    super.connectedCallback();

    validateChartPropsArray(this.data, 'data');

    this._isRTL = getRTL(this);

    this.initializeData();
    this.renderChart();
  }

  private initializeData() {
    if (this.variant === Variant.SingleBar) {
      this._hydrateData();
    }
    this.hydrateLegends();
  }

  public renderChart() {
    const chartContainerDiv = d3Select(this.chartContainer);
    chartContainerDiv
      .selectAll('div')
      .data(this.data!)
      .enter()
      .append('div')
      .each((d, i, nodes) => {
        this.createSingleChartBars(d, i, nodes);
      });
  }

  private createSingleChartBars(singleChartData: ChartProps, index: number, nodes: any) {
    const singleChartBars = this._createBarsAndLegends(singleChartData!, index);

    // create a div element. Loop through chart bars and add to the div as its children
    const divEle = d3Select(nodes[index])
      .attr('key', index)
      .attr('id', `_MSBC_bar-${index}`)
      .node()!
      .appendChild(singleChartBars.node());
  }

  private hydrateLegends() {
    // Create a map to store unique legends
    const uniqueLegendsMap = new Map();

    // Iterate through all chart points and populate the map
    for (const dataSeries of this.data) {
      for (const point of dataSeries.chartData!) {
        if ((point as any).placeholder === true) {
          continue;
        }
        // Check if the legend is already in the map
        if (!uniqueLegendsMap.has(point.legend)) {
          uniqueLegendsMap.set(point.legend, {
            legend: point.legend,
            data: point.data,
            color: point.gradient ? point.gradient[0] : point.color,
          });
        }
      }
    }

    // Convert the map values back to an array
    this.uniqueLegends = Array.from(uniqueLegendsMap.values());
  }

  private _hydrateData() {
    this.data!.forEach(({ chartTitle, chartData }) => {
      if (chartData!.length === 1) {
        const pointData = chartData![0];
        const newEntry = {
          legend: '',
          data: pointData.total! - pointData.data! > 0 ? pointData.total! - pointData.data! : 0,
          y: pointData.total!,
          color: '#edebe9',
          placeholder: true,
        };
        chartData!.push(newEntry);
      }
    });
  }

  private calculateBarSpacing(): number {
    const svgWidth = this.rootDiv.getBoundingClientRect().width;
    let barSpacing = 0;
    const MARGIN_WIDTH_IN_PX = 3;
    if (svgWidth) {
      const currentBarSpacing = (MARGIN_WIDTH_IN_PX / svgWidth) * 100;
      barSpacing = currentBarSpacing;
    }
    return barSpacing;
  }

  public _createBarsAndLegends(data: ChartProps, barNo?: number) {
    const _isRTL = this._isRTL;
    const _computeLongestBarTotalValue = () => {
      let longestBarTotalValue = 0;
      this.data!.forEach(({ chartData, chartTitle }) => {
        const barTotalValue = chartData!.reduce(
          (acc: number, point: ChartDataPoint) => acc + (point.data ? point.data : 0),
          0,
        );
        longestBarTotalValue = Math.max(longestBarTotalValue, barTotalValue);
      });
      return longestBarTotalValue;
    };
    const longestBarTotalValue = _computeLongestBarTotalValue();
    const noOfBars =
      data.chartData?.reduce((count: number, point: ChartDataPoint) => (count += (point.data || 0) > 0 ? 1 : 0), 0) ||
      1;
    const barSpacingInPercent = this.calculateBarSpacing();
    const totalMarginPercent = barSpacingInPercent * (noOfBars - 1);
    // calculating starting point of each bar and it's range
    const startingPoint: number[] = [];
    const barTotalValue = data.chartData!.reduce(
      (acc: number, point: ChartDataPoint) => acc + (point.data ? point.data : 0),
      0,
    );
    const total = this.variant === Variant.AbsoluteScale ? longestBarTotalValue : barTotalValue;

    let sumOfPercent = 0;
    data.chartData!.map((point: ChartDataPoint, index: number) => {
      const pointData = point.data ? point.data : 0;
      const currValue = (pointData / total) * 100;
      let value = currValue ? currValue : 0;

      if (value < 1 && value !== 0) {
        value = 1;
      } else if (value > 99 && value !== 100) {
        value = 99;
      }
      sumOfPercent += value;

      return sumOfPercent;
    });

    // Include an imaginary placeholder bar with value equal to
    // the difference between longestBarTotalValue and barTotalValue
    // while calculating sumOfPercent to get correct scalingRatio for absolute-scale variant
    if (this.variant === Variant.AbsoluteScale) {
      let value = total === 0 ? 0 : ((total - barTotalValue) / total) * 100;
      if (value < 1 && value !== 0) {
        value = 1;
      } else if (value > 99 && value !== 100) {
        value = 99;
      }
      sumOfPercent += value;
    }

    /**
     * The %age of the space occupied by the margin needs to subtracted
     * while computing the scaling ratio, since the margins are not being
     * scaled down, only the data is being scaled down from a higher percentage to lower percentage
     * Eg: 95% of the space is taken by the bars, 5% by the margins
     * Now if the sumOfPercent is 120% -> This needs to be scaled down to 95%, not 100%
     * since that's only space available to the bars
     */

    const scalingRatio = sumOfPercent !== 0 ? sumOfPercent / (100 - totalMarginPercent) : 1;

    let prevPosition = 0;
    let value = 0;

    const createBars = (g: SVGGElement, point: ChartDataPoint, index: number) => {
      const barHeight = 12;
      const pointData = point.data ? point.data : 0;
      if (index > 0) {
        prevPosition += value;
      }
      value = (pointData / total) * 100 ? (pointData / total) * 100 : 0;
      if (value < 1 && value !== 0) {
        value = 1 / scalingRatio;
      } else if (value > 99 && value !== 100) {
        value = 99 / scalingRatio;
      } else {
        value = value / scalingRatio;
      }

      startingPoint.push(prevPosition);

      const gEle = d3Select(g) // 'this' refers to the current 'g' element
        .attr('key', index)
        .attr('role', 'img')
        .attr('aria-label', pointData);

      let gradientId = '';
      if (point.gradient) {
        const defs = document.createElementNS(SVG_NAMESPACE_URI, 'defs');
        gEle.node()!.appendChild(defs);

        const linearGradient = document.createElementNS(SVG_NAMESPACE_URI, 'linearGradient');
        defs.appendChild(linearGradient);
        gradientId = `gradient-${barNo}-${index}`;
        linearGradient.setAttribute('id', gradientId);

        const stop1 = document.createElementNS(SVG_NAMESPACE_URI, 'stop');
        linearGradient.appendChild(stop1);
        stop1.setAttribute('offset', '0%');
        stop1.setAttribute('stop-color', point.gradient[0]);

        const stop2 = document.createElementNS(SVG_NAMESPACE_URI, 'stop');
        linearGradient.appendChild(stop2);
        stop2.setAttribute('offset', '100%');
        stop2.setAttribute('stop-color', point.gradient[1]);
      }
      gEle;
      const rect = gEle
        .append('rect')
        .attr('key', index)
        .attr('id', `${barNo}-${index}`)
        .attr('barinfo', `${point.legend}`)
        .attr('class', 'bar')
        .attr('style', point.gradient ? `fill:url(#${gradientId})` : `fill:${point.color!}`)
        .attr(
          'x',
          `${
            _isRTL
              ? 100 - startingPoint[index] - value - barSpacingInPercent * index
              : startingPoint[index] + barSpacingInPercent * index
          }%`,
        )
        .attr('y', 0)
        .attr('width', value + '%')
        .attr('height', barHeight)
        .attr('tabindex', 0);
      this._bars.push(rect.node()!);
    };

    const containerDiv = d3Create('div').attr('style', 'position: relative');

    const chartTitleDiv = containerDiv.append('div').attr('class', 'chart-title-div');
    chartTitleDiv
      .append('div')
      .append('span')
      .attr('class', 'chart-title')
      .text(data?.chartTitle ? data?.chartTitle : '');

    const showChartDataText = this.variant !== Variant.AbsoluteScale;
    // chartData length is always 2 in single-bar variant
    const showRatio = !this.hideRatio && data!.chartData!.length === 2;
    const getChartData = () => (data!.chartData![0].data ? data!.chartData![0].data : 0);

    if (showChartDataText) {
      if (data.chartDataText) {
        const chartTitleRight = document.createElement('div');
        chartTitleDiv.node()!.appendChild(chartTitleRight);
        chartTitleRight.classList.add('chart-data-text');
        chartTitleRight.textContent = data.chartDataText;
      } else if (showRatio) {
        const ratioDiv = chartTitleDiv.append('div').attr('role', 'text');
        const numData = data!.chartData![0].data;
        const denomData = data!.chartData![1].data;
        const total = numData! + denomData!;
        ratioDiv.append('span').attr('class', 'ratio-numerator').text(numData!);
        ratioDiv.append('span').attr('class', 'ratio-denominator').text(`/${total!}`);
      }
    }

    const svgDiv = containerDiv.append('div').attr('style', 'display: flex;');
    const svgEle = svgDiv
      .append('svg')
      .attr('height', 12)
      .attr('width', 100 + '%')
      .attr('class', 'svg-chart')
      .attr('aria-label', data?.chartTitle ? data?.chartTitle : '')
      .selectAll('g')
      .data(data.chartData!)
      .enter()
      .append('g')
      .each(function (this, d, i) {
        createBars(this, d, i);
      })
      .on('mouseover', (event, d) => {
        if (d && d.hasOwnProperty('placeholder') && (d as any).placeholder === true) {
          return;
        }

        const bounds = this.rootDiv.getBoundingClientRect();
        const centerX = window.innerWidth / 2;
        const xPos = Math.max(0, Math.min(centerX, window.innerWidth));

        this.tooltipProps = {
          isVisible: true,
          legend: d.legend,
          yValue: `${d.data}`,
          color: d.gradient ? d.gradient[0] : d.color!,
          xPos: this._isRTL ? bounds.right - event.clientX : Math.min(event.clientX - bounds.left, xPos),
          yPos: event.clientY - bounds.top - 40,
        };
      })
      .on('mouseout', () => {
        this.tooltipProps = { isVisible: false, legend: '', yValue: '', color: '', xPos: 0, yPos: 0 };
      });

    if (this.variant === Variant.AbsoluteScale) {
      const showLabel = true;
      const barLabel = barTotalValue;
      if (showLabel) {
        if (Math.round((startingPoint[startingPoint.length - 1] || 0) + value + totalMarginPercent) === 100) {
          svgDiv
            .append('text')
            .attr('key', 'text')
            .attr('style', 'margin-top: -4.5px; margin-left: 2px;')
            .attr('class', 'bar-label')
            .attr(
              'x',
              `${
                this._isRTL
                  ? 100 - (startingPoint[startingPoint.length - 1] || 0) - value - totalMarginPercent
                  : (startingPoint[startingPoint.length - 1] || 0) + value + totalMarginPercent
              }%`,
            )
            .attr('textAnchor', 'start')
            .attr('y', this.barHeight / 2 + 6)
            .attr('dominantBaseline', 'central')
            .attr('transform', `translate(${this._isRTL ? -4 : 4})`)
            .attr('aria-label', `Total: ${barLabel}`)
            .attr('role', 'img')
            .text(barLabel);
        } else {
          svgEle
            .append('text')
            .attr('key', 'text')
            .attr('class', 'bar-label')
            .attr(
              'x',
              `${
                this._isRTL
                  ? 100 - (startingPoint[startingPoint.length - 1] || 0) - value - totalMarginPercent
                  : (startingPoint[startingPoint.length - 1] || 0) + value + totalMarginPercent
              }%`,
            )
            .attr('textAnchor', 'start')
            .attr('y', this.barHeight / 2 + 6)
            .attr('dominantBaseline', 'central')
            .attr('transform', `translate(${this._isRTL ? -4 : 4})`)
            .attr('aria-label', `Total: ${barLabel}`)
            .attr('role', 'img')
            .text(barLabel);
        }
      }
    }

    if (data.benchmarkData) {
      const benchmarkContainer = document.createElement('div');
      containerDiv.node()!.appendChild(benchmarkContainer);
      benchmarkContainer.classList.add('benchmark-container');

      const triangle = document.createElement('div');
      benchmarkContainer.appendChild(triangle);
      triangle.classList.add('triangle');

      const benchmarkRatio = (data.benchmarkData / total) * 100;
      triangle.style['insetInlineStart'] = `calc(${benchmarkRatio}% - 4px)`;
    }

    return containerDiv;
  }

  public handleLegendMouseoverAndFocus = (legendTitle: string) => {
    if (this.isLegendSelected) {
      return;
    }

    this.activeLegend = legendTitle;
  };

  public handleLegendMouseoutAndBlur = () => {
    if (this.isLegendSelected) {
      return;
    }

    this.activeLegend = '';
  };

  public handleLegendClick = (legendTitle: string) => {
    if (this.isLegendSelected && this.activeLegend === legendTitle) {
      this.activeLegend = '';
      this.isLegendSelected = false;
    } else {
      this.activeLegend = legendTitle;
      this.isLegendSelected = true;
    }
  };

  public activeLegendChanged = (oldValue: string, newValue: string) => {
    if (newValue === '') {
      this._bars?.forEach(bar => bar.classList.remove('inactive'));
    } else {
      this._bars?.forEach(bar => {
        if (bar.getAttribute('barinfo') === newValue) {
          bar.classList.remove('inactive');
        } else {
          bar.classList.add('inactive');
        }
      });
    }
  };
}
