// apps/stress-test/src/shared/wc/TestAdd.ts
import { TestOptions } from '../utils/testOptions';
import { WCSelectorTree } from './WCSelectorTree';
import { WCTestTree } from './types';
import { SelectorTreeNode } from '../tree/types';
import { DOMSelectorTreeComponentRenderer } from '../vanilla/types';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';

export class TestAdd extends HTMLElement implements WCTestTree {
  constructor(
    tree: SelectorTreeNode,
    selectors: string[],
    componentRenderer: DOMSelectorTreeComponentRenderer,
    testOptions: TestOptions,
  ) {
    super();

    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }

    const domTree = new WCSelectorTree(componentRenderer, testOptions);
    domTree.tree = tree;
    this.appendChild(domTree);

    setTimeout(() => {
      const addDomTree = new WCSelectorTree(componentRenderer, testOptions);
      addDomTree.tree = tree;
      this.appendChild(addDomTree);
      requestAnimationFrame(() => performanceMeasure());
    }, 2000);
  }
}

window.customElements.define('wc-test-add', TestAdd);

// apps/stress-test/src/shared/react/TestAdd.tsx
import * as React from 'react';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';
import { ReactSelectorTree } from './ReactSelectorTree';
import type { TestProps } from './types';

export const TestAdd: React.FC<TestProps> = ({ tree, selectors, componentRenderer, testOptions }) => {
  const [added, setAdded] = React.useState(false);

  React.useEffect(() => {
    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }
  }, []);

  React.useEffect(() => {
    setTimeout(() => {
      setAdded(true);
      performanceMeasure();
    }, 2000);
  }, []);

  return (
    <>
      <ReactSelectorTree tree={tree} componentRenderer={componentRenderer} />
      {added && <ReactSelectorTree tree={tree} componentRenderer={componentRenderer} />}
    </>
  );
};
