// apps/stress-test/src/shared/wc/TestInjectStyles.ts
import { TestOptions } from '../utils/testOptions';
import { WCSelectorTree } from './WCSelectorTree';
import { WCTestTree } from './types';
import { SelectorTreeNode } from '../tree/types';
import { DOMSelectorTreeComponentRenderer } from '../vanilla/types';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';

export class TestInjectStyles extends HTMLElement implements WCTestTree {
  constructor(
    tree: SelectorTreeNode,
    selectors: string[],
    componentRenderer: DOMSelectorTreeComponentRenderer,
    testOptions: TestOptions,
  ) {
    super();

    const domTree = new WCSelectorTree(componentRenderer, testOptions);
    domTree.tree = tree;
    this.appendChild(domTree);

    setTimeout(() => {
      styleInjector(selectors);
      performanceMeasure();
    }, 2000);
  }
}

window.customElements.define('wc-test-inject-styles', TestInjectStyles);

// apps/stress-test/src/shared/react/TestInjectStyles.tsx
import * as React from 'react';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';
import { ReactSelectorTree } from './ReactSelectorTree';
import type { TestProps } from './types';

export const TestInjectStyles: React.FC<TestProps> = ({ tree, selectors, componentRenderer }) => {
  React.useEffect(() => {
    setTimeout(() => {
      styleInjector(selectors);
      performanceMeasure();
    }, 2000);
  }, []);

  return <ReactSelectorTree tree={tree} componentRenderer={componentRenderer} />;
};
