// apps/stress-test/src/shared/wc/TestRemoveAll.ts
import { TestOptions } from '../utils/testOptions';
import { WCSelectorTree } from './WCSelectorTree';
import { WCTestTree } from './types';
import { SelectorTreeNode } from '../tree/types';
import { DOMSelectorTreeComponentRenderer } from '../vanilla/types';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';

export class TestRemoveAll extends HTMLElement implements WCTestTree {
  constructor(
    tree: SelectorTreeNode,
    selectors: string[],
    componentRenderer: DOMSelectorTreeComponentRenderer,
    testOptions: TestOptions,
  ) {
    super();

    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }

    const domTree = new WCSelectorTree(componentRenderer, testOptions);
    domTree.tree = tree;
    this.appendChild(domTree);

    setTimeout(() => {
      domTree.tree = null;
      requestAnimationFrame(() => performanceMeasure());
    }, 2000);
  }
}

window.customElements.define('wc-test-remove-all', TestRemoveAll);

// apps/stress-test/src/shared/react/TestRemoveAll.tsx
import * as React from 'react';
import { styleInjector } from '../css/injectStyles';
import { performanceMeasure } from '../utils/performanceMeasure';
import { ReactSelectorTree } from './ReactSelectorTree';
import type { TestProps } from './types';

export const TestRemoveAll: React.FC<TestProps> = ({ tree, selectors, componentRenderer, testOptions }) => {
  const [theTree, setTheTree] = React.useState<TestProps['tree'] | undefined>(tree);

  React.useEffect(() => {
    if (testOptions.withStyles === 'true') {
      styleInjector(selectors);
    }
  }, []);

  React.useEffect(() => {
    if (theTree === undefined && tree) {
      setTheTree(tree);

      setTimeout(() => {
        setTheTree(undefined);
        performanceMeasure();
      }, 2000);
    }
  }, [tree]);

  return <ReactSelectorTree tree={theTree} componentRenderer={componentRenderer} />;
};
